name: Workflow for my_app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing gcc package
        run: |
          sudo apt update -y
          sudo apt install build-essential -y

      - name: Running code
        working-directory: ./app
        run: |
          g++ file.cpp -o file.gpp
          ./file.gpp

          
        
