name: Workflow for my-app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print message
        run: echo "Hello world!"
        
      - name: Install of gcc packages
        run: |
          sudo apt update -y
          sudo apt install build-essential -y

      - name: Run of code
        working-directory: ./app
        run: |
          g++ file.cpp -o file.gpp
          ./file.gpp

          
        
    

    
